### ISSUE TITLE
SharingWithFileCoordinator

### ISSUE THREAD

**Issue by dimohamdy** [NatashaTheRobot/watchkit#1]
Data not Saved in File
I try to trace this bug in TodoListTableViewController.swift -> saveTodoItem and Data not saved and 
length of list still 0  in  " tableView(tableView: UITableView, numberOfRowsInSection section: Int)"
thanks

**Comment by pdhlnpt** [comment]
you have to create your app id and your group , you can't use the natasha app id and her group. Because you use hers so when you run the code, application can not create presentedItemURL so they can not save the data. i got your error when i tried to learn from natasha code. Thanks Natasha for her tutorial.

**Comment by dimohamdy** [comment]
Thanks
